-- SQL Script to generate 15 demo blog posts with 2026 HOT TREND TAGS
-- Copy and run this in your Supabase SQL Editor

DELETE FROM public.blogs WHERE title LIKE 'Bài viết mẫu%';

INSERT INTO public.blogs (title, excerpt, content, image_url, tags, featured)
VALUES 
('Bài viết mẫu 1: Tương lai của Human-Centric Design', 'Khám phá tại sao thiết kế hướng con người và tính chân thực sẽ lên ngôi trong năm 2026.', 'Nội dung chi tiết về Human-Centric Design...', 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&q=80&w=800', ARRAY['Human-Centric'], true),
('Bài viết mẫu 2: AI-Partnered: Khi AI trở thành đồng nghiệp', 'Cách designer cộng tác với AI để tăng hiệu suất mà không mất đi bản sắc cá nhân.', 'Phân tích về AI trong quy trình sáng tạo...', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800', ARRAY['AI-Partnered'], false),
('Bài viết mẫu 3: Sự trỗi dậy của Neo-Minimalism', 'Tối giản không còn nhàm chán với sự kết hợp của màu sắc táo bạo và Typography mạnh mẽ.', 'Khám phá phong cách Neo-Minimalism...', 'https://images.unsplash.com/photo-1586717791821-3f44a563cc4c?auto=format&fit=crop&q=80&w=800', ARRAY['Neo-Minimalism'], false),
('Bài viết mẫu 4: Spatial UI và kỷ nguyên của chiều sâu', 'Thiết kế giao diện 3D và các lớp không gian đang thay đổi cách chúng ta tương tác.', 'Tìm hiểu về Spatial UI...', 'https://images.unsplash.com/photo-1505330622279-bf7d7fc918f4?auto=format&fit=crop&q=80&w=800', ARRAY['Spatial UI'], false),
('Bài viết mẫu 5: Motion Kinetic: Ngôn ngữ của sự chuyển động', 'Typography động và các yếu tố kinetic đang trở thành tiêu chuẩn mới cho branding.', 'Hướng dẫn về Motion Kinetic...', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800', ARRAY['Motion Kinetic'], false),
('Bài viết mẫu 6: Eco-Design và tính bền vững trong thiết kế', 'Sử dụng màu sắc tự nhiên và chất liệu hữu cơ để bảo vệ môi trường thông qua nghệ thuật.', 'Chi tiết về Eco-Design...', 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=800', ARRAY['Eco-Design'], false),
('Bài viết mẫu 7: Retro-Futurism: Nhìn về tương lai qua lăng kính quá khứ', 'Sự pha trộn giữa niềm lạc quan thập niên 60 và công nghệ tương lai.', 'Khám phá Retro-Futurism...', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800', ARRAY['Retro-Futurism'], false),
('Bài viết mẫu 8: Experimental Type: Phá vỡ mọi giới hạn chữ viết', 'Khi Typography không còn chỉ để đọc mà còn để cảm nhận thị giác.', 'Phân tích Experimental Type...', 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=800', ARRAY['Experimental Type'], false),
('Bài viết mẫu 9: Chaos Branding: Nghệ thuật của sự náo nhiệt', 'Tại sao Maximalism và sự hỗn độn có kiểm soát lại thu hút khách hàng Gen Z và Alpha.', 'Tìm hiểu về Chaos Branding...', 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&q=80&w=800', ARRAY['Chaos Branding'], false),
('Bài viết mẫu 10: Tactile Visuals: Chạm vào thiết kế qua màn hình', 'Sử dụng texture và bề mặt vật liệu để tạo cảm giác xúc giác chân thực cho digital design.', 'Hướng dẫn tạo Tactile Visuals...', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80&w=800', ARRAY['Tactile Visuals'], false),
('Bài viết mẫu 11: Ứng dụng AI trong việc tạo Texture tự nhiên', 'Làm thế nào để kết hợp trí tuệ nhân tạo và xúc giác vật lý.', 'Workflow sáng tạo mới...', 'https://images.unsplash.com/photo-1626785774625-ddc7c82a1e5e?auto=format&fit=crop&q=80&w=800', ARRAY['AI-Partnered', 'Tactile Visuals'], false),
('Bài viết mẫu 12: Typography động trong Spatial UI', 'Khi chữ viết bay bổng trong không gian 3 chiều.', 'Kỹ thuật thiết kế mới...', 'https://images.unsplash.com/photo-1589365278144-c9e705f843ba?auto=format&fit=crop&q=80&w=800', ARRAY['Motion Kinetic', 'Spatial UI'], false),
('Bài viết mẫu 13: Minimalist bền vững cho thương hiệu Xanh', 'Sự kết hợp giữa lối sống tối giản và ý thức sinh thái.', 'Case study Eco-Design...', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800', ARRAY['Neo-Minimalism', 'Eco-Design'], false),
('Bài viết mẫu 14: Retro-Future: Màu sắc của năm 2026', 'Dự đoán những bảng màu Gradient sẽ thống trị thị trường.', 'Xu hướng màu sắc 2026...', 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800', ARRAY['Retro-Futurism'], false),
('Bài viết mẫu 15: Tính nhân bản trong kỷ nguyên sỗ', 'Giữ vững giá trị Human-Centric giữa làn sóng công nghệ.', 'Tư duy thiết kế 2026...', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800', ARRAY['Human-Centric'], false);
